version: '3.8'
services:
  mysqldb:
    image: "mysql:8.0.33"
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shopmt
      MYSQL_USER: shopmt
      MYSQL_PASSWORD: password
    restart: always
    ports:
      - 3307:3306
    networks:
      - db
    volumes:
      - ./springboot-backend/shopmt/backup.sql:/docker-entrypoint-initdb.d/backup.sql
  
  backend:
    container_name: backend-spring-boot
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/shopmt?autoReconnect=true
    build: 
      context: ./springboot-backend/shopmt
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8081:8081
    networks:
      - db
    depends_on:
      - mysqldb

  frontend:
    container_name: frontend-reactjs
    build: 
      context: ./reactjs-frontend/shopmt
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend

networks:
  db:
    driver: bridge

volumes:
  db:

      