version: '3.8'
services:
  mysqldb:
    image: "mysql:8.0.33"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: shopmt
      MYSQL_USER: shopmt
      MYSQL_PASSWORD: 123456
    volumes:
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
  backend:
    container_name: backend-spring-boot
    build: 
      context: ./springboot-backend/shopmt
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mysqldb
  frontend:
    container_name: frontend-reactjs
    build: 
      context: ./reactjs-frontend/shopmt
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend

      