name: CI/CD

on:
   push:
      branches: [master]

jobs:
   deploy:
      runs-on:
         - aws-ec2
      steps:
       - name: Deploy EC2
         run: |
           if [ -d "personal-project" ]; then
             cd personal-project
             git pull https://github.com/TranMinhMan040702/personal-project.git && echo "Pull successful"
             cd ../
           else
             git clone https://github.com/TranMinhMan040702/personal-project.git && echo "Clone successful"
           fi
           cd personal-project/
           sudo docker ps -a --format '{{.ID}}' | xargs -r sudo docker rm
           sudo docker-compose up -d --build
